import json
import re
import shutil
import subprocess
from datetime import datetime
from pathlib import Path
from urllib.parse import urlparse

from .constants import LOGS_DIR, NUCLEI_TIMEOUT_SECONDS
from .storage import extract_cves, make_finding, record_findings, record_scan
from .targets import normalize_web_urls
from .utils import json_dumps, slugify


def nuclei_severity_to_bluejay(severity: str) -> str:
    mapping = {
        "critical": "Critical",
        "high": "High",
        "medium": "Medium",
        "low": "Low",
        "info": "Info",
    }
    return mapping.get(severity.lower(), "Unknown")


def parse_nuclei_jsonl(output_path: Path, target: str) -> list[dict]:
    findings = []

    if not output_path.exists():
        return findings

    for line in output_path.read_text(encoding="utf-8", errors="ignore").splitlines():
        try:
            record = json.loads(line)
        except json.JSONDecodeError:
            continue

        info = record.get("info", {}) if isinstance(record, dict) else {}
        name = info.get("name") or record.get("template-id") or "Nuclei finding"
        severity = nuclei_severity_to_bluejay(str(info.get("severity", "unknown")))
        matched_at = str(record.get("matched-at") or record.get("host") or target)
        template_id = str(record.get("template-id", "unknown-template"))
        remediation = (
            info.get("remediation")
            or info.get("description")
            or "Verify the finding, patch or reconfigure the affected service, and retest."
        )
        evidence_parts = [
            f"Template: {template_id}",
            f"Matched: {matched_at}",
        ]

        extracted = record.get("extracted-results")
        if extracted:
            evidence_parts.append(f"Extracted: {extracted}")

        curl_command = record.get("curl-command")
        if curl_command:
            evidence_parts.append("Validation request was generated by Nuclei; review raw output before replaying manually.")

        findings.append(
            make_finding(
                target=target,
                title=str(name),
                severity=severity,
                finding_type="nuclei-template",
                evidence="\n".join(evidence_parts),
                source=str(output_path),
                recommendation=str(remediation),
                confidence="Medium",
                cves=extract_cves(json_dumps(record)),
                metadata={
                    "template_id": template_id,
                    "matched_at": matched_at,
                    "nuclei_type": record.get("type", ""),
                },
            )
        )

    return findings


def run_nuclei_scan(target: str, severity: str = "info,low,medium,high,critical") -> Path | None:
    urls = normalize_web_urls(target)

    if urls is None:
        print("Nuclei target blocked.")
        print("Use an allowed hostname/IP or a simple HTTP/HTTPS URL.")
        return None

    if shutil.which("nuclei") is None:
        print("Nuclei is not installed or not available in PATH.")
        print("Install Nuclei separately, then rerun this command.")
        return None

    hostname = urlparse(urls[0]).hostname or target
    timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    output_path = LOGS_DIR / f"nuclei-{slugify(hostname)}-{timestamp}.jsonl"
    temp_target_path = LOGS_DIR / f"nuclei-targets-{slugify(hostname)}-{timestamp}.txt"
    temp_target_path.write_text("\n".join(urls) + "\n", encoding="utf-8")
    command = [
        "nuclei",
        "-list",
        str(temp_target_path),
        "-jsonl",
        "-o",
        str(output_path),
        "-severity",
        severity,
        "-rate-limit",
        "10",
        "-timeout",
        "5",
        "-retries",
        "1",
        "-no-color",
    ]

    print(f"\nRunning bounded Nuclei scan against: {hostname}")
    print("Command:", " ".join(command))
    print()

    try:
        result = subprocess.run(
            command,
            text=True,
            capture_output=True,
            timeout=NUCLEI_TIMEOUT_SECONDS,
        )
    except subprocess.TimeoutExpired:
        print("Nuclei timed out before the scan completed.")
        record_scan(hostname, "nuclei", "nuclei", "timeout", command, output_path, "")
        return None

    if result.returncode != 0:
        print("Nuclei returned an error:")
        print(result.stderr.strip() or result.stdout.strip())
        record_scan(
            hostname,
            "nuclei",
            "nuclei",
            "failed",
            command,
            output_path,
            "",
            {"stderr": result.stderr.strip(), "stdout": result.stdout.strip()},
        )
        return None

    record_scan(hostname, "nuclei", "nuclei", "completed", command, output_path, "")
    print(f"Nuclei output saved to: {output_path}")
    record_findings(parse_nuclei_jsonl(output_path, hostname), str(output_path))
    return output_path
